### ISSUE TITLE
Improvements wish-list for the pretty-printer

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1152]
I've run into the following issues:

- [ ] Names in Prims are prefixed with `Prims`, e.g. `int` is printed as `Prims.int` (mentioned in #36 as well)
- [ ] Names in the current module are prefixed with the name the current module, e.g. `Test.a` when printing `let a = 1` from module `test`.  This might be more general (maybe names are not minimized before printing?)
- [ ] Terms are not normalized/beta-reduced before printing error messages or goals, leading to things like `blah has type "(fun x y z t -> int) x y z t"`. Concrete example: `Prims.squash (Test.a ((fun ab bc wc -> 0) ab bc wc))`
- [ ] There's an extra space in unification variable names: `uu___unification_ 102 ab bc wc`
- [ ] Internally generated names are ugly `uu__unification 25`, `uu___202013`, etc.
- [ ] Internally generated names are printed even when unused: the type of `let aaa () = 1` prints as ` uu___711553:Prims.unit -> Prims.Tot Prims.int`
- [ ] Normalization produces extra ascriptions (not directly printing-related) #1132
