### ISSUE TITLE
September work items

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#1522]
This is a meta-issue to track a few main bits of feature work that we are tackling in the next few weeks, hoping to demo some of the results at our "all-hands" meeting in September.

We track progress on the specific points below in other issues, but will report a summary of the progress here.

- [ ] `fstar --indent` @victor-dumitrescu. We aim to use this feature to automatically "beautify" concrete syntax, with a first goal being to apply this to all files in FStar/ulib. We track progress in issue #1298 

- [ ] Monotonic buffers @aseemr: LowStar.Buffer to support indexing with preorders, witness/recall etc. We track progress in #1420 

- [ ] Typeclasses and a fix to the unifier @mtzguido. The unifier picks solutions that are sometimes too specific, hindering typeclass resolution. We track progress in #1486 

- [ ] Incremental extraction and cross-module inlining @nikswamy. We aim to support inlining of symbols marked `inline_for_extraction` across interface boundaries. We track progress in #1444

**Comment by mtzguido** [comment]
First of all, note the F* syntax highlighting in this post!! Seems Github has shipped it.

Here's a prototype for calc statements. The `calc_eq` type is probably unneeded, but I felt it was cleaner and it is, as far as I remember, how Agda does it too. The proofs are backwards here since, e.g., `step` needs `z` before we can even state the proof argument. Some desugaring could help. 

```fstar
module Calc

open FStar.Tactics

type calc_eq #t : t -> t -> Type =
  | CalcRefl : #x:t -> calc_eq x x
  | CalcStep : #x:t -> #y:t -> #z:t -> calc_eq x y -> squash (y == z) -> calc_eq x z

let rec elim_calc_eq #t (#x #y : t) (p : calc_eq x y) : Lemma (x == y) =
  match p with
  | CalcRefl -> ()
  | CalcStep p' _ -> elim_calc_eq p'

let init (#t:Type) (x:t) : calc_eq x x = CalcRefl

let step (#t:Type) (#x #y z : t) (_ : squash (y == z)) (p : calc_eq x y) : calc_eq x z =
  CalcStep p ()

let finish (#t:Type) (#x #y :t) (p : calc_eq x y) : squash (x == y) = elim_calc_eq p

let a_proof =
  finish (step 6 () (init (1 + 2 + 3)))

let comm (#x #y : int) : squash (x + y == y + x) = ()

let bigger_proof (c:int) (h : unit -> squash (c == 42)) : squash (c + 2 + 3 == 47) =
  finish (
  step 47 () (
  step (5 + 42) (h ()) (
  step (5 + c) comm (
  step (c + 5) () (
  init (c + 2 + 3))))))

open FStar.Mul
open FStar.Tactics.Canon

let with_a_tactic (c:int) : squash (2 * (c + 3) == 7 * c - 5 * (c - 1) + 1) =
  finish (
  step (7 * c - 5 * (c - 1) + 1) (_ by (dump "1"; canon ())) (
  step (2 * c + 6) (_ by (dump "2"; canon ())) (
  init (2 * (c + 3)))))
```
