### ISSUE TITLE
Steel work items

### ISSUE THREAD

**Issue by R1kM** [FStarLang/FStar#2243]
Recapping here the list of Steel work items

** Code Refactoring **
- [ ] Replace SteelAtomic unobservable and SteelAtomic observable by SteelGhost and SteelAtomic
- [ ] Add an Atomic version of SteelSel
- [ ] Replace all uses of Steel by SteelSel, and rename SteelSel (and variants) into Steel
- [ ] Unify tactics in SteelSel.Common and Steel.Common
- [ ] Add refinement in post-memory to include validity of precondition, so as to avoid repeating it
- [ ] Use selectors in Queue/DoublyLinkedList
- [ ] Move stable examples to ulib/experimental
- [ ] Wrap up Steel.Array library
- [ ] Clean up the different versions of SteelSel.change_slprop

** (Layered) Effects improvements **
- [ ] Allow the use of unconstrained implicits in subcomp and if_then_else for framing and SMT rewrites (#2234)
- [ ] Improve composition between different effects in if/then/else (#2220)

** Framing tactic improvements **
- [ ] Add special support for sladmit (#2239)
- [ ] Add special support for pure predicates (#2235)
- [ ] Make code more resistant when SMT fallback is called while being disabled (i.e. with the predicate already resolved to True)
- [ ] Provide better error message when unification fails (should not happen, please report)

** IDE support **
- [ ] Remove spurious warnings about implicit not resolved when they are resolved by tactic
- [ ] Fix ranges (and underscored code snippet) when an assertion fails
- [ ] Provide meaningful error message and range when the SMT query in smt_fallback fails
- [ ] Only open fstar:goals buffer in a debug mode when tactic fails.
- [ ] Provide information about the current slprop context from Emacs

** Other **
- [ ] Allow native extraction to C
- [ ] How do we remove "reifiable" from the Steel effect for extraction to OCaml?
- [ ] Inspect SMT queries (especially the large number of small queries generated)

** F* issues **
- [ ] Fix CheckNoUvars error in IDE ( #2213 )
- [ ] Fix segfaults when calling the tactic (#2209)
- [ ] Correctly propagate implicit arg qualifiers in Rel.imitate_app (PR #2238 )
- [ ] Allow the generation of SMT guards when calling the unifier through a variant of trefl (PR #2240 )

**Comment by aseemr** [comment]
See https://github.com/FStarLang/FStar/pull/2256 for dependent pattern matching
