### ISSUE TITLE
A few things to make it easier to implement IDEs for F*

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#344]
Hi all,

Here are a few things that I found imperfect as I was working on F\* interactive support for Emacs. Some of this overlaps #341 slightly.
- [x] Indenting continuation lines of error messages would make them easier to parse [EDIT: Fixed; I used a parsing trick instead]
- [x] The error formats between the interactive mode and the non-interactive mode seem to be slightly different; in particular, the interactive mode seems to only have one error format, with no `ERROR` or `WARNING` header. The non-interactive one seems to have two formats.
- [ ] In interactive mode, errors are still reported by line and column. If they were reported by offset instead (number of characters), it would be much easier to track and display them.
- [x] When the top-level module is missing, one gets a quite dramatic error message:
  
  ```
  Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
  Failure("Unset current module")
  ```

Cheers,
Clément.

**Comment by cpitclaudel** [comment]
fstar-mode doesn't care about the CLI anymore, and F*'s assumptions about lines and columns is pretty deeply baked in, so let's close this :)
