### ISSUE TITLE
Master issue tracker for miTLS extraction

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#483]
This meta-issue sums up all the sub-issues that I'm encountering on my branch trying to extract all of miTLS.
- [ ] **(worked around)** two functions that return `bytes`; the `bytes` type has been marked as `opaque` by myself in my last F\* commit; the functions have no type annotation; somehow, the type annotation in the generated code talks about `seq uint8` instead of the type `bytes` that should remain _abstract_; see mitls/mitls-fstar@4a90c83 and mitls/mitls-fstar@3f96eb4

NS: Now that we have it, we should mark write 'abstract type bytes = seq uint8`.
- [x]  a new issue popped up recently; if I don't specify all implicit arguments in a few locations with `encrypt #i #ad #rg ...` then F\* crashes; see mitls/mitls-fstar@1462fda438104dcbc2eeb7a320523a4ad0947686 for my workarounds

NS: This one seems to be a problem with type inference leaving an unresolved implicit argument in the term. The treatment of implicit arguments in the default type-checker is a mess. This was revamped significantly in the --universes mode. Adapting those features to the main type checker is a lost cause. I will probably not fix this one and work instead on making it possible to move to --universes.

NS: Update ... ok, I'm going to take a closer look at this now. Perhaps it is a relatively easy fix

NS: Escalating this to a separate sub-issue below. 
- [x]  old issue related to implicit arguments that were giving a hard crash; see comment at https://github.com/mitls/mitls-fstar/blob/jonathan/src/tls/TestRecord.fst#L50

NS: It this the same as the previous issue?

NS: This is also fixed now, in two ways. 
1. If you leave out the implicit arguments, you get an "unresolved implicits" error as expected.
2. Actually, it's not possible to infer the peer_region argument of AEAD_GCM.State and StatefulLHAE.State. The reason you had to provide all 4 arguments explicitly is because instantiation of implicits is positional and you can't write `_` for implicit term arguments (you can in --universes). So, I changed it to make the peer_region argument explicit. Then, in TestRecord, the remaining three arguments are inferred properly.
- [x] **(worked around)** `type foo` should be disallowed (should be `assume type foo`?); mitls/mitls-fstar@9d5f30b

NS: This should be fixed now by ab50009d8a30b72f00131174bf35936616f8216e
- [x] the miTLS development generates references to `FStar_Heap` even though it's using `HyperHeap.fst`? is that normal?
- [ ] **(worked around)** when extracting `FStar.Heap.fst`, extraction generates a reference to a non-existent `FStar_Heap_Ref` module (see https://github.com/FStarLang/FStar/issues/483#issuecomment-182154450)
- [X] the issue with unification variables and implicit term arguments has resurfaced https://github.com/FStarLang/FStar/issues/483#issuecomment-182155580

NS: Fixed.

@nikswamy I'll keep updating this issue description as I encounter more extraction issues; the `FStar_Heap_Ref` one is the one you'll hit if you try `make tls-gen` from my branch.

For reference: some minor commits I've had to perform on FStar itself: https://github.com/FStarLang/FStar/commit/5ea5ab08e50257e62b48c0dfa85d23dadb74adff, https://github.com/FStarLang/FStar/commit/eb3274bf96a83f9ead7fcbab86a62fd2e6e68179

**Comment by msprotz** [comment]
### About `FStar.Heap.fst`

Two sub-sub-issues.
- `type heap` should be `assume type heap`, correct?
- here's the generated code that contains a wacky reference to `FStar_Heap_Ref`:

```
let ___Ref___r : aref  ->  Prims.unit FStar_Heap_Ref.a ref = (fun projectee -> (Obj.magic ((match (projectee) with
| Ref (_, _5_4) -> begin
_5_4
end))))
```

This should be without `FStar_Heap_Ref.a`, i.e.:
```
let ___Ref___r : aref  ->  Prims.unit ref = (fun projectee -> (Obj.magic ((match (projectee) with
| Ref (_, _5_4) -> begin
_5_4
end))))
```

**Comment by msprotz** [comment]
### Issue with unification variables and implicit term arguments

Working around all the issues, I get to a point where:

```
let encrypt i ad rg (State #ii #r #region #peer_region log seqn key) f =
  let n = !seqn in
```

is extracted to

```
(let n = (FStar_ST.op_Bang ((fun i ad rg _50_225 f ii r region peer_region log seqn key -> region) i ad rg _50_225 f () () region peer_region log seqn key) seqn)
in (let l = (FStar_ST.op_Bang ((fun i ad rg _50_225 f ii r region peer_region log seqn key n -> if (r = TLSInfo.Reader) then begin
peer_region
```

which the issue we talked about earlier.

**Comment by nikswamy** [comment]
This last issue is fixed now. Inasmuch as it now produces type and functionally correct, if very inefficient code. We really should normalize more before extraction.

**Comment by nikswamy** [comment]
### Issue with unresolved implicits causing extraction to crash

Here below is a minimized version of the problem from `Content.fst`.

If you check it with `fstar --codegen OCaml test.fst` it fails safely with an error:

```
test.fst(14,14-14,26) : Error
Unresolved implicit argument
```

If, however, you provide the `--lax` flag (as is done in make tls-gen), then the check for the unresolved implicit argument is bypassed and we go straight to (unsafe) codegen ... which then blows up. 

```
module Test
new type id
new type range
new type bytes

type pre_fragment (i:id) = bytes

val ghost_repr: #i:id -> pre_fragment i -> GTot bytes
let ghost_repr #i f = f

type fragment (i:id) (rg:range) = f:pre_fragment i { True }

val h : i:id -> rg:range -> fragment i rg -> GTot bytes
let h i g f = ghost_repr f
```

**Comment by msprotz** [comment]
Ok, I successfully extracted and compiled everything. I still can't drive the record layer because there's some missing bits but at least everything builds and runs.

**Comment by catalin-hritcu** [comment]
@msprotz  This is 1 year old now, can it be closed or is there anything interesting left  here?
