### ISSUE TITLE
Work items for the universes release

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#505]
**Relatively independent items that could be picked up by others**:
  - [ ] Migrate the ocaml version to use sedlex with unicode support for lexing (F# version already supports it). Allow the use of unicode identifiers and infix operators. Use \times for multiplication.
  - [x] Fix extraction of try/with to really use OCaml's try/with rather than FStar.All.tryWith. The current extraction causes partial pattern matching on exceptions to fail incorrectly.
  - [x] Provide a way to denote universes beyond Type0 and universe abstractions
  - [x] Tailcalls disabled via tail ghost code (which gets erased to unit, rather than being erased altogether ... cf. the optimizations of let below)
  - [x] assume val f: t -> ST unit ...
    
    is extracted to let f _ = ()
    rather than     let f _ = failwith ""
    
    Leads to unexpected non-failing but incorrect output
  - [x] Translate (x:unit) to ()
  - [x] Optimize (let x = () in e) to e
  - [x] Optimize (let x = e in x) to e
  - [x] Optimize (let x : unit = e in ()) to e
  - [x] Optimize (let x : unit = e in e') to e;e'
  - [ ] Remove unused top-level definitions private to a module 
    Maybe not for the next release
  - [x] Ghost unit <: Pure unit
  - [ ] Precedence-aware pretty printing and indentation
    Maybe not for the next release
  - [x] Make: FStar.ST.get : unit -> Tot (erased heap)
     Or, better, change sel, upd etc. to GTot functions
  - [ ] Removing redundant units (changing arity is non-trivial)
    Maybe not for the next release
- [x] Seems like F\* interactive still dies when there is a parsing error
  at the dep analysis stage

OUTPUT [Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("hd")
]
- [ ] Better support for bitvectors
    Either via Z3 bv sorts
    Or, via FStar.Seq.seq bool (would need support for division, modulo etc. to work well)
  Maybe not for the next release
- [x] opaque is deprecated ... emit a warning
- [ ] damn temp_no_proj still seems to be needed in some places
- [ ] reproduce interactive weirdness by trying sbuffer.fst, type abuffer
  without the "temp_no_proj" option, and then add it

Unable to reproduce this right now. : (
- [x] assume new type should introduce the type in Type0, by default (burned us many times already)

**Aseem**
- [x] `HasEq` cf. #510 

**Nik**:
- [x] Bootstrap the compiler in --universes
  Maybe not for the next release
- [x] Remove code for the stratified type-checker
  Maybe not for the next release
- [x] examples/algorithms/GC.fst has a TODO in it for an unnecessary eta expansio
- [ ] examples/algorithms/downgrade.fst is not yet verified
    examples/unit-tests/universes/inverse.fst is excluded .. resurrect it
    In general, search diff unit-tests/universes against unit-tests to see how things needed to be changed and review
- [ ] investigate removing or minimizing ADD_EQ_REFINEMENT for pure applications in tc.fs
- [x] Implicit arguments: Allow type arguments to have ghost effect

```
assume val f : int -> GTot int
assume type t : int -> Type
assume val g : int -> Type
let h (x:t (f 0)) =  x=x
```

Fails with Implicit argument: Expected a total term; got a ghost term: (Test.t (Test.f 0))

Even with an explicit annotation, it fails:

```
     val h : t (f 0) -> Tot bool
     let h (x:t (f 0)) = op_Equality #(t (f 0)) x x
```
- [x] Universes for mutually inductive datatypes are incorrectly generalized

```
type t =
  | MkT : s -> t
and s =
  | MkS : t -> s
```

is universe polymorphic, when Type0 would do

Here's the current error for this (pointing at `MkT`):

```
Expected expression of type "Module.s";
got expression "_0" of type "Module.s"
```
- [x] PRF.fst lax checks and extracts
- [x] Handshake.fst: extracted successfully
- [x]  Connection.fst: lax checks, but not verified yet
- [x]  TLS.fst: lax checks and extracts
- [x] Implement the positivity check
- [ ] Really encode nested let recs to the solver
- [ ] Report the sub-term that causes the effect of a term to be higher than expected
  Maybe not for the next release
- [x] Bisecting error labels in SMTEncoding for a more precise error report.
- [x] Instrumenting the post-condition in an SMT query to report specific clauses in it that are unprovable
- [ ] Extend free var computation in ToSyntax to include missing forms (i.e., more complete support for the `'a` notation for type variables)
- [ ] Uvar applications in pattern are needlessly rechecked,
  e.g., 
  Checking pattern expression (Prims.None #(?133719 i ad x c x x log seqn key h0 n ad' x)) against expected type (Prims.option (AEAD_GCM.dplain i ad' c))
  C:\Users\nswamy\workspace\mitls-fstar\src\tls\StatefulLHAE.fst(300,6-300,10) (Tm_meta)
  C:\Users\nswamy\workspace\mitls-fstar\src\tls\StatefulLHAE.fst(300,6-300,10) (Tm_app)
  (C:\Users\nswamy\workspace\mitls-fstar\src\tls\StatefulLHAE.fst(300,6-300,10)) Checking app (Prims.None #(?133719 i ad x c x x log seqn key h0 n ad' x))
  C:\Users\nswamy\workspace\mitls-fstar\src\tls\StatefulLHAE.fst(300,6-300,10) (Tm_fvar: Prims.None)
  Return comp type is Tot (#.a:Type -> Tot (Prims.option a@0))
  (C:\Users\nswamy\workspace\mitls-fstar\src\tls\StatefulLHAE.fst(300,6-300,10)) Type of head is (#.a:Type -> Tot (Prims.option a@0))
  Checking arg (Tm_app) (?133719 i ad x c x x log seqn key h0 n ad' x) at type Type
  C:\Users\nswamy\workspace\mitls-fstar\src\tls\StatefulLHAE.fst(300,6-300,10) (Tm_app)
  (C:\Users\nswamy\workspace\mitls-fstar\src\tls\StatefulLHAE.fst(300,6-300,10)) Checking app (?133719 i ad x c x x log seqn key h0 n ad' x)
  C:\Users\nswamy\workspace\mitls-fstar\src\tls\StatefulLHAE.fst(300,6-300,10) (Tm_uvar)
- [x] fix `#pragma` inasmuch as possible

**Jonathan**:
- [x] new semantics for interfaces (including auto-deps fixup)

**Samin**:
- [x] Migrate all code in examples and doc/tutorial to stop using --stratified
  See #565
- [ ] A better pretty-printer in FStar.Syntax.Print. See #36 
- [x] Uniquely number warnings and errors.

**Comment by nikswamy** [comment]
Some of those remaining work items have now been implemented, others still remain open. Closing this issue as this release is long since done.
