### ISSUE TITLE
Improve quality of crypto tutorials

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#611]
The crypto examples of the F\* tutorial are outdated and badly explained:
https://www.fstar-lang.org/tutorial/tutorial.html#sec-cryptography-examples
- [ ] Better explanation of the MAC example
- [x] Update capabilities based access control example
- [x] Update secure remote procedure call example (RPC)
- [x] Add working Encrypt-then-MAC example (https://github.com/FStarLang/FStar/issues/643)
- [ ] Add working Stateful Authenticated Encryption example (https://github.com/FStarLang/FStar/issues/644)

**Comment by markulf** [comment]
See also https://github.com/FStarLang/FStar/issues/565

**Comment by nikswamy** [comment]
Revamping crypto examples as a case study for the new tutorial would be welcome. But this one is obsolete.
