### ISSUE TITLE
F* release for POPL 2017

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#770]
Since all deadlines just passed, we should now have enough time to tackle the following cleanup issues (roughly sorted in decreasing order of importance/significance):

# Merging branches
- [ ] kyod_parser
Ready to go
  - [ ] blog/wiki post

- [ ] c_record_aead (Nik trying)
Passing regression test in low-level crypto
Set this for nightly-build only in master
Will merge at first opportunity

- [ ] taramana_local_open, projectors, name_resolution, include
In that order
We settled on Some?.x for projectors and Some? for discriminators
  - [ ] name resolution with more intuitive scope management
  - [ ] dependency generation
  - [ ] include (#691)

# Bootstrap
- [ ] remove --stratified **P1** timeline: end of the 2016
   - [ ] Supporting recursive type abbreviations
   - [ ] Pushing code through the new type-checker and extraction machinery
- Improving the bootstrap process: **P2** by January 15, 2017
  - [ ] remove duplicate bootstrap libraries, etc.
  - [ ] use autodeps

# Compiler usability **P2** by January 15, 2017
- [ ] F* as a driver for the OCaml compiler

# Concrete syntax
- [ ] pretty-printer (#764) **P1** (protz, kenji, tomer)
  - [ ] Printing the front-end syntax (timeline Jan 15, 2017)
  - [ ] Transforming syntax.term to ast.term (timeline something basic by Jan 15; continuing)
- [ ] documented official concrete syntax **P2** by end of 2016
- [ ] switch to sedlex **P3** by January 15, 2017 (protz)
- [ ] manual universe instantiation **P1** by end of 2016 
- [ ] ascription syntax **P3** (precedence of <: ) asap (kenji)
       We want `(fun x -> e <: t)` to mean `(fun x -> (e <: t))`.

# Libraries
- [ ] improved libraries (naming conventions, etc.) (#687) **P1** Jan 15, 2017 Tahina
  - [ ] Seq and SeqProperties merged using include
  - [ ] List.Tot and ListProperties
  - [ ] documented libraries (#273, #635 ) (using fsdoc syntax, not necessarily producing pretty html)
- [ ] fsdoc (#634) Post pretty printer
- [ ] Integer overloading using FStar.Integers ongoing
- [ ] Making the heap models uniform (Aseem) ongoing

# dm4free
- [ ] indexed effects (https://github.com/FStarLang/FStar/wiki/Indexed-effects) **P1** 
- [ ] dm4free (#753) **P1** by Jan 15, plus ongoing for relational and monotonicity

# Z3
- [ ] Z3 non-time-based resource limits (#767) **P1** timeline: two weeks
- [ ] Z3 process pool for OCaml **P3** nice to have

# Misc
- [ ] positivity (Aseem) **P1** By Jan 15th
- [ ] interactive mode with interfaces (add `interface` keyword) **P1** Jan 15th
- [ ] default effect Tot **P1** By Jan 15th
- [ ] F# compatibility (#746) **P3**  nice to have

**Comment by catalin-hritcu** [comment]
Should clarify how this is related to #505 and the past but not completely achieved "Universes Release" milestone (https://github.com/FStarLang/FStar/milestone/3).

**Comment by nikswamy** [comment]
Can we close this issue now? Perhaps creating separate issues for some of the tasks that are still to be completed. WDYT @catalin-hritcu ?

**Comment by catalin-hritcu** [comment]
@nikswamy Creating separate issues for things here that are still open and useful then closing this sounds good to me.

**Comment by catalin-hritcu** [comment]
In general, our meta issues have been living forever, but it would be great if some of them could be closed with the remaining tasks turned into separate issues. In this case, I have no clue which ones of these tasks are still useful, but someone working closer on the implementation should know.

As for the roadmap, I've renamed it to [A roadmap for F* (Jan Feb 2017)](https://github.com/FStarLang/FStar/wiki/A-roadmap-for-F*-(Jan-Feb-2017)) so that it's clearer that that's an old document.
